server:
    port: 9011


spring:
    application:
        name: bankaccount-service
    datasource:
      url : jdbc:mysql://db-internet-bank:3306/bankaccount?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=UTC
      username : root
      password : root 
      initialization-mode : always
    jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL8Dialect
    jpa.hibernate.ddl-auto : create-drop
    security.user.name : root
    security.user.password: root

#Swagger
swagger.api.info.title : microservice-bankAccount
swagger.api.info.description : Project for Customers
swagger.api.info.version : 0.0.1-SNAPSHOT
    

retry.maxAttempts : 5
retry.backOffPeriod : 2000


message:
 source:
  basename: classpath:message/message.properties
  use.code.as.default.message: true
